--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 3/14/2024 1:40:22 PM
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS shop;

CREATE DATABASE IF NOT EXISTS shop
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE shop;

--
-- Create table `supplier`
--
CREATE TABLE IF NOT EXISTS supplier (
  Id char(36) NOT NULL,
  Code char(100) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  SupplierProductId char(36) DEFAULT NULL,
  Address text DEFAULT NULL,
  Phone char(100) DEFAULT NULL,
  Email varchar(255) DEFAULT NULL,
  Country varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Status int DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `category`
--
CREATE TABLE IF NOT EXISTS category (
  Id char(36) NOT NULL,
  Code char(100) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  ParentId char(36) DEFAULT NULL,
  Discription text DEFAULT NULL,
  Avatar text DEFAULT NULL,
  Hot int DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE category
ADD CONSTRAINT category_ibfk_1 FOREIGN KEY (ParentId)
REFERENCES category (Id);

--
-- Create table `brand`
--
CREATE TABLE IF NOT EXISTS brand (
  Id char(36) NOT NULL,
  Code char(100) NOT NULL DEFAULT '',
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Country varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Status int DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `product`
--
CREATE TABLE IF NOT EXISTS product (
  Id char(36) NOT NULL,
  Code char(100) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Avatar text DEFAULT NULL,
  TotalSold int DEFAULT NULL,
  AverageStar decimal(2, 1) UNSIGNED DEFAULT NULL,
  Hot int DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  CategoryId char(36) DEFAULT NULL,
  BrandId char(36) DEFAULT NULL,
  SupplierId char(36) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE product
ADD CONSTRAINT product_ibfk_1 FOREIGN KEY (CategoryId)
REFERENCES category (Id);

--
-- Create foreign key
--
ALTER TABLE product
ADD CONSTRAINT product_ibfk_2 FOREIGN KEY (BrandId)
REFERENCES brand (Id);

--
-- Create foreign key
--
ALTER TABLE product
ADD CONSTRAINT product_ibfk_3 FOREIGN KEY (SupplierId)
REFERENCES supplier (Id);

--
-- Create table `productdetail`
--
CREATE TABLE IF NOT EXISTS productdetail (
  Id char(36) NOT NULL,
  ProductId char(36) DEFAULT NULL,
  Name varchar(255) DEFAULT NULL,
  Brand varchar(255) DEFAULT NULL,
  InfoDetail longtext DEFAULT NULL,
  Discription longtext DEFAULT NULL,
  TotalSell int DEFAULT NULL,
  TotalRating int DEFAULT NULL,
  TotalStar int DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE productdetail
ADD CONSTRAINT productdetail_ibfk_1 FOREIGN KEY (ProductId)
REFERENCES product (Id);

--
-- Create table `productimage`
--
CREATE TABLE IF NOT EXISTS productimage (
  Id char(36) NOT NULL,
  ProductDetailId char(36) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Path varchar(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ProductId` on table `productimage`
--
ALTER TABLE productimage
ADD INDEX ProductId (ProductDetailId);

--
-- Create foreign key
--
ALTER TABLE productimage
ADD CONSTRAINT productimage_ibfk_1 FOREIGN KEY (ProductDetailId)
REFERENCES productdetail (Id);

--
-- Create table `role`
--
CREATE TABLE IF NOT EXISTS role (
  Id char(36) NOT NULL,
  Code int DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Discription text DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `user`
--
CREATE TABLE IF NOT EXISTS user (
  Id char(36) NOT NULL,
  Code char(100) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Password varchar(255) DEFAULT NULL,
  RoleId char(36) DEFAULT NULL,
  Avatar text DEFAULT NULL,
  FullName varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Gender tinyint DEFAULT NULL,
  PhoneNumber char(100) DEFAULT NULL,
  Address text DEFAULT NULL,
  Age tinyint DEFAULT NULL,
  Email varchar(255) DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  RefreshToken varchar(5000) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT user_ibfk_1 FOREIGN KEY (RoleId)
REFERENCES role (Id);

--
-- Create table `viewedproduct`
--
CREATE TABLE IF NOT EXISTS viewedproduct (
  Id char(36) NOT NULL,
  ProductId char(36) DEFAULT NULL,
  UserId char(36) DEFAULT NULL,
  Date datetime DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE viewedproduct
ADD CONSTRAINT viewedproduct_ibfk_1 FOREIGN KEY (ProductId)
REFERENCES product (Id);

--
-- Create foreign key
--
ALTER TABLE viewedproduct
ADD CONSTRAINT viewedproduct_ibfk_2 FOREIGN KEY (UserId)
REFERENCES user (Id);

--
-- Create table `shoppingcartitem`
--
CREATE TABLE IF NOT EXISTS shoppingcartitem (
  Id char(36) NOT NULL,
  UserId char(36) DEFAULT NULL,
  ProductsDetailId char(36) DEFAULT NULL,
  Quantity int DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE shoppingcartitem
ADD CONSTRAINT shoppingcartitem_ibfk_1 FOREIGN KEY (UserId)
REFERENCES user (Id);

--
-- Create foreign key
--
ALTER TABLE shoppingcartitem
ADD CONSTRAINT shoppingcartitem_ibfk_2 FOREIGN KEY (ProductsDetailId)
REFERENCES productdetail (Id);

--
-- Create table `rating`
--
CREATE TABLE IF NOT EXISTS rating (
  Id char(36) NOT NULL,
  Stars int DEFAULT NULL,
  Content text DEFAULT NULL,
  ProductsId char(36) DEFAULT NULL,
  UserId char(36) DEFAULT NULL,
  RatingAt datetime DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE rating
ADD CONSTRAINT rating_ibfk_1 FOREIGN KEY (ProductsId)
REFERENCES product (Id);

--
-- Create foreign key
--
ALTER TABLE rating
ADD CONSTRAINT rating_ibfk_2 FOREIGN KEY (UserId)
REFERENCES user (Id);

--
-- Create table `comment`
--
CREATE TABLE IF NOT EXISTS comment (
  Id char(36) NOT NULL,
  ParentId char(36) DEFAULT NULL,
  Content text DEFAULT NULL,
  Star tinyint UNSIGNED DEFAULT NULL,
  ProductId char(36) NOT NULL DEFAULT '',
  UserId char(36) NOT NULL DEFAULT '',
  CommentAt datetime DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ProductsId` on table `comment`
--
ALTER TABLE comment
ADD INDEX ProductsId (ProductId);

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_1 FOREIGN KEY (ParentId)
REFERENCES comment (Id);

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_2 FOREIGN KEY (ProductId)
REFERENCES product (Id);

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_3 FOREIGN KEY (UserId)
REFERENCES user (Id);

--
-- Create table `variation`
--
CREATE TABLE IF NOT EXISTS variation (
  Id char(36) NOT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Discription text DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `paymenttype`
--
CREATE TABLE IF NOT EXISTS paymenttype (
  Id char(36) NOT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `variationoptiongroup`
--
CREATE TABLE IF NOT EXISTS variationoptiongroup (
  Id char(36) NOT NULL DEFAULT '',
  Discription text DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `variationoption`
--
CREATE TABLE IF NOT EXISTS variationoption (
  Id char(36) NOT NULL,
  VariationId char(36) DEFAULT NULL,
  VariationOptionGroupId char(36) DEFAULT NULL,
  Value varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE variationoption
ADD CONSTRAINT variationoption_ibfk_1 FOREIGN KEY (VariationId)
REFERENCES variation (Id);

--
-- Create foreign key
--
ALTER TABLE variationoption
ADD CONSTRAINT variationoption_ibfk_2 FOREIGN KEY (VariationOptionGroupId)
REFERENCES variationoptiongroup (Id);

--
-- Create table `productconfiguration`
--
CREATE TABLE IF NOT EXISTS productconfiguration (
  Id char(36) NOT NULL,
  ProductId char(36) DEFAULT NULL,
  ProductImageId char(36) DEFAULT NULL,
  VariationOptionGroupId char(36) DEFAULT NULL,
  Price decimal(19, 2) DEFAULT NULL,
  Inventory int DEFAULT NULL,
  SKU varchar(255) DEFAULT NULL,
  AverageStar tinyint DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE productconfiguration
ADD CONSTRAINT productconfiguration_ibfk_3 FOREIGN KEY (ProductImageId)
REFERENCES productimage (Id);

--
-- Create foreign key
--
ALTER TABLE productconfiguration
ADD CONSTRAINT productconfiguration_ibfk_4 FOREIGN KEY (VariationOptionGroupId)
REFERENCES variationoptiongroup (Id);

--
-- Create foreign key
--
ALTER TABLE productconfiguration
ADD CONSTRAINT productconfiguration_ibfk_5 FOREIGN KEY (ProductId)
REFERENCES product (Id);

--
-- Create table `orderstatus`
--
CREATE TABLE IF NOT EXISTS orderstatus (
  Id char(36) NOT NULL,
  Status int DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `order`
--
CREATE TABLE IF NOT EXISTS `order` (
  Id char(36) NOT NULL,
  Code char(100) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  UserId char(36) DEFAULT NULL,
  UserPaymentMethodId char(36) DEFAULT NULL,
  ShippingtFee double DEFAULT NULL,
  ShippingAddress text DEFAULT NULL,
  TotalPrice double DEFAULT NULL,
  OrderStatus char(36) DEFAULT NULL,
  OrderDate datetime DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE `order`
ADD CONSTRAINT order_ibfk_1 FOREIGN KEY (UserId)
REFERENCES user (Id);

--
-- Create foreign key
--
ALTER TABLE `order`
ADD CONSTRAINT order_ibfk_2 FOREIGN KEY (OrderStatus)
REFERENCES orderstatus (Id);

--
-- Create table `userpaymentmethod`
--
CREATE TABLE IF NOT EXISTS userpaymentmethod (
  Id char(36) NOT NULL,
  OrderId char(36) DEFAULT NULL,
  UserId char(36) DEFAULT NULL,
  PaymentTypeId char(36) DEFAULT NULL,
  Provider varchar(255) DEFAULT NULL,
  AccountNumber char(255) DEFAULT NULL,
  IsDefault tinyint DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE userpaymentmethod
ADD CONSTRAINT userpaymentmethod_ibfk_1 FOREIGN KEY (OrderId)
REFERENCES `order` (Id);

--
-- Create foreign key
--
ALTER TABLE userpaymentmethod
ADD CONSTRAINT userpaymentmethod_ibfk_2 FOREIGN KEY (UserId)
REFERENCES user (Id);

--
-- Create foreign key
--
ALTER TABLE userpaymentmethod
ADD CONSTRAINT userpaymentmethod_ibfk_3 FOREIGN KEY (PaymentTypeId)
REFERENCES paymenttype (Id);

--
-- Create table `orderitem`
--
CREATE TABLE IF NOT EXISTS orderitem (
  Id char(36) NOT NULL,
  OrderId char(36) DEFAULT NULL,
  ProductDetailId char(36) DEFAULT NULL,
  Price double DEFAULT NULL,
  Quantity int DEFAULT NULL,
  TotalPrice double DEFAULT NULL,
  ProductName varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  ProductAvatar varchar(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE orderitem
ADD CONSTRAINT orderitem_ibfk_1 FOREIGN KEY (OrderId)
REFERENCES `order` (Id);

--
-- Create foreign key
--
ALTER TABLE orderitem
ADD CONSTRAINT orderitem_ibfk_2 FOREIGN KEY (ProductDetailId)
REFERENCES productdetail (Id);

--
-- Create table `orderhistorystatus`
--
CREATE TABLE IF NOT EXISTS orderhistorystatus (
  Id char(36) NOT NULL,
  OrderId char(36) DEFAULT NULL,
  StatusId char(36) DEFAULT NULL,
  Date datetime DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE orderhistorystatus
ADD CONSTRAINT orderhistorystatus_ibfk_1 FOREIGN KEY (OrderId)
REFERENCES `order` (Id);

--
-- Create foreign key
--
ALTER TABLE orderhistorystatus
ADD CONSTRAINT orderhistorystatus_ibfk_2 FOREIGN KEY (StatusId)
REFERENCES orderstatus (Id);

--
-- Create table `discount`
--
CREATE TABLE IF NOT EXISTS discount (
  Id char(36) NOT NULL,
  Code char(100) DEFAULT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Type int DEFAULT NULL,
  Value double DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  StartDate datetime DEFAULT NULL,
  EndDate datetime DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `productdiscount`
--
CREATE TABLE IF NOT EXISTS productdiscount (
  Id char(36) NOT NULL,
  DiscountId char(36) DEFAULT NULL,
  ProductsId char(36) DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE productdiscount
ADD CONSTRAINT productdiscount_ibfk_1 FOREIGN KEY (DiscountId)
REFERENCES discount (Id);

--
-- Create foreign key
--
ALTER TABLE productdiscount
ADD CONSTRAINT productdiscount_ibfk_2 FOREIGN KEY (ProductsId)
REFERENCES product (Id);

--
-- Create table `categorydiscount`
--
CREATE TABLE IF NOT EXISTS categorydiscount (
  Id char(36) NOT NULL,
  DiscountId char(36) DEFAULT NULL,
  CategoryId char(36) DEFAULT NULL,
  Status tinyint DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE categorydiscount
ADD CONSTRAINT categorydiscount_ibfk_1 FOREIGN KEY (DiscountId)
REFERENCES discount (Id);

--
-- Create foreign key
--
ALTER TABLE categorydiscount
ADD CONSTRAINT categorydiscount_ibfk_2 FOREIGN KEY (CategoryId)
REFERENCES category (Id);

--
-- Create table `slice`
--
CREATE TABLE IF NOT EXISTS slice (
  Id char(36) NOT NULL,
  Name varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  Avatar text DEFAULT NULL,
  Link text DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `Proc_User_NewCode`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_User_NewCode ()
COMMENT 'lấy mã mới cho user'
BEGIN
  DECLARE MaxCode bigint;
  DECLARE NewUserCode text;
  -- Tìm mã nhân viên có số lớn nhất trong db
  SELECT
    MAX(CAST(SUBSTRING(Code, 2) AS UNSIGNED)) INTO MaxCode
  FROM user u;

  -- Nếu không tìm thấy mã nào, gán giá trị ban đầu
  IF MaxCode IS NULL THEN
    SET MaxCode = 0;
  END IF;

  -- nếu mã đến giới hạn trả về -1
  IF MaxCode = 99999999999999999 THEN
    SET NewUserCode = '-1';
    SELECT
      NewUserCode;
  ELSE
    -- tăng mã lên 1
    SET NewUserCode = CONCAT('u', MaxCode + 1);
    SELECT
      NewUserCode;
  END IF;
END
$$

DELIMITER ;

-- 
-- Dumping data for table supplier
--
INSERT INTO supplier VALUES
('08dc2386-8a38-48f5-8c73-4e2d33c3b665', 'C1', 'Hà Thành', NULL, 'Hà nội', '09123456789', 'hathanh@gmail.com', 'Vietnam', NULL);

-- 
-- Dumping data for table category
--
INSERT INTO category VALUES
('05d028da-a53f-11ee-981a-34e6d767255e', 'DH4', 'Phụ kiện đồng hồ', '1ac89524-a53e-11ee-981a-34e6d767255e', 'Các loại phụ kiện thay thế, lắp ráp cho đồng hồ', '', 0, 1),
('11d62eac-a53c-11ee-981a-34e6d767255e', 'DT', 'Điện thoại', NULL, 'Các loại điện thoại', '', 0, 1),
('153fde9c-a53d-11ee-981a-34e6d767255e', 'DT2', 'Điện thoại phổ thông', '11d62eac-a53c-11ee-981a-34e6d767255e', 'Các loại điện thoại phím, có các tính năng cơ bản: nghe, gọi, nhắn tin đơn giản', '', 0, 1),
('1ac89524-a53e-11ee-981a-34e6d767255e', 'DH', 'Đồng hồ', NULL, 'Các loại đồng hồ', '', 0, 1),
('3ed60390-a53e-11ee-981a-34e6d767255e', 'DH1', 'Đồng hồ nam', '1ac89524-a53e-11ee-981a-34e6d767255e', 'Các loại đồng hồ dành cho nam giới', '', 0, 1),
('62ec32b4-a53e-11ee-981a-34e6d767255e', 'DH3', 'Đồng hồ nữ', '1ac89524-a53e-11ee-981a-34e6d767255e', 'Các loại đồng hồ dành cho nữ giới', '', 0, 1),
('9db74c9d-a53d-11ee-981a-34e6d767255e', 'DT3', 'Điện thoại bàn', '11d62eac-a53c-11ee-981a-34e6d767255e', 'Các loại điện thoại để bàn dành cho văn phòng hoặc để tại nhà', '', 0, 1),
('c18aea4a-a53c-11ee-981a-34e6d767255e', 'DT1', 'Điện thoại Smartphone', '11d62eac-a53c-11ee-981a-34e6d767255e', 'Các loại điện thoại thông minh, cảm ứng, nhiều tính năng giải chí và làm việc', '', 0, 1);

-- 
-- Dumping data for table brand
--
INSERT INTO brand VALUES
('08dc1384-6947-416b-83f1-b740a1144535', 'br2', 'samsung', 'VN', 1),
('08dc241c-29d8-403c-850a-906976825193', 'brandTest', 'Test', 'VN', 0),
('08dc241c-2a16-4f07-877f-af274ab6a013', 'brandTest', 'Test', 'VN', 0),
('ced5d38d-a58c-11ee-a784-34e6d767255e', 'Br1', 'Apple', 'Mĩ', 1);

-- 
-- Dumping data for table product
--
-- Table shop.product does not contain any data (it is empty)

-- 
-- Dumping data for table role
--
INSERT INTO role VALUES
('a85ef86d-da59-11ee-b006-34e6d767255e', 0, 'Admin', 'Have all permission', 0),
('a85f30a6-da59-11ee-b006-34e6d767255e', 1, 'User', 'Have some permission', 0);

-- 
-- Dumping data for table productdetail
--
-- Table shop.productdetail does not contain any data (it is empty)

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('08dbf798-9d39-4898-88ec-5718d88ab1f7', 'u1', 'Quang', '$2a$11$As5bp/GO1f8NDDh3LwrrNeZIkIw4AzuH1CehARjdLG3SgmxFYPitu', 'a85ef86d-da59-11ee-b006-34e6d767255e', '/a.jpg', 'Trương Mạnh Quang', 0, '123456789', 'Hà nội', 21, 'quang@gmail.com', 1, 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzOTdhZDU5NC05MGVhLTQxZTItODA4Ni1iNzlkZGI1NTUwMDIiLCJ0b2tlbl90eXBlIjoicmVmcmVzaCIsInN1YiI6InF1YW5nQGdtYWlsLmNvbSIsImVtYWlsIjoicXVhbmdAZ21haWwuY29tIiwibmJmIjoxNzA5ODg1MDcwLCJleHAiOjE3MTI0NzcwNzAsImlhdCI6MTcwOTg4NTA3MCwiaXNzIjoiaHR0cHM6Ly9zaG9wLmNvbS8iLCJhdWQiOiJodHRwczovL3Nob3AuY29tLyJ9.-XgBezRf_1RNPAb7AJtFghC3MDXnDBtx4i-YO5PqhJR6RwtXNL1-eh09NFcOjRUKwhieerFBYIw8-2QBF-QcpQ'),
('08dc3cf5-2e2d-4060-8e63-0a0d7ef876e6', 'u2', '', '$2a$11$IpH1Ym0d9f8VCU/OtrDQHuVSB0sSJA/8BBReFgdgpXnzti/znhJlu', NULL, 'string', 'string', 0, 'string', 'string', 0, 'string', 1, NULL);

-- 
-- Dumping data for table variation
--
INSERT INTO variation VALUES
('08dc24e9-4822-4fcf-8172-ba65be673147', 'Color', NULL),
('08dc24e9-4823-4e4a-8624-8be8273b1136', 'RAM', NULL);

-- 
-- Dumping data for table paymenttype
--
-- Table shop.paymenttype does not contain any data (it is empty)

-- 
-- Dumping data for table variationoptiongroup
--
-- Table shop.variationoptiongroup does not contain any data (it is empty)

-- 
-- Dumping data for table productimage
--
-- Table shop.productimage does not contain any data (it is empty)

-- 
-- Dumping data for table orderstatus
--
-- Table shop.orderstatus does not contain any data (it is empty)

-- 
-- Dumping data for table `order`
--
-- Table shop.`order` does not contain any data (it is empty)

-- 
-- Dumping data for table discount
--
-- Table shop.discount does not contain any data (it is empty)

-- 
-- Dumping data for table viewedproduct
--
-- Table shop.viewedproduct does not contain any data (it is empty)

-- 
-- Dumping data for table variationoption
--
-- Table shop.variationoption does not contain any data (it is empty)

-- 
-- Dumping data for table userpaymentmethod
--
-- Table shop.userpaymentmethod does not contain any data (it is empty)

-- 
-- Dumping data for table slice
--
-- Table shop.slice does not contain any data (it is empty)

-- 
-- Dumping data for table shoppingcartitem
--
-- Table shop.shoppingcartitem does not contain any data (it is empty)

-- 
-- Dumping data for table rating
--
-- Table shop.rating does not contain any data (it is empty)

-- 
-- Dumping data for table productdiscount
--
-- Table shop.productdiscount does not contain any data (it is empty)

-- 
-- Dumping data for table productconfiguration
--
-- Table shop.productconfiguration does not contain any data (it is empty)

-- 
-- Dumping data for table orderitem
--
-- Table shop.orderitem does not contain any data (it is empty)

-- 
-- Dumping data for table orderhistorystatus
--
-- Table shop.orderhistorystatus does not contain any data (it is empty)

-- 
-- Dumping data for table comment
--
-- Table shop.comment does not contain any data (it is empty)

-- 
-- Dumping data for table categorydiscount
--
-- Table shop.categorydiscount does not contain any data (it is empty)

--
-- Set default database
--
USE shop;

DELIMITER $$

--
-- Create trigger `Averange_Star_Comment_Trigger`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER Averange_Star_Comment_Trigger
AFTER INSERT
ON comment
FOR EACH ROW
BEGIN
  DECLARE total_star mediumint UNSIGNED;
  DECLARE total_rating mediumint UNSIGNED;
  DECLARE avg_star decimal(2, 1) UNSIGNED;

  -- Tính tổng số star đánh giá của sản phẩm
  SELECT
    SUM(c.Star),
    COUNT(*) INTO total_star, total_rating
  FROM shop.comment c
  WHERE c.ProductId = NEW.ProductId;

  -- Tính trung bình số sao đánh giá của sản phẩm
  IF total_star IS NULL THEN
    SET avg_star = 0;
  ELSE
    SET avg_star = total_star / total_rating;
  END IF;

  -- Cập nhật trung bình số sao đánh giá vào bảng product
  UPDATE shop.product p
  SET p.AverageStar = avg_star
  WHERE p.Id = NEW.ProductId;
END
$$

DELIMITER ;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;